import React,{useState,useEffect,useRef,useMemo} from 'react';
import {MATERIALS,materialsPrompt,parseMaterials,sourceChanged,highlightedPoints,mergeSlides,slideState} from './sermon-outputs.js';
import {assistantSystem} from './assistant-profile.js';
import {DOCUMENT_ASSISTANT_SYSTEM,assistantRewriteHtml} from './document-assistant.js';
import {exportBlob,downloadBlob} from './document-export.js';
export function SermonOutputPanel({t,editor,outputs={},getCurrent,captureSource,onUpdate,onJump,onClose,profile,disabled}){
  const [tab,setTab]=useState('export'),[layout,setLayout]=useState('manuscript'),[source,setSource]=useState(null),[current,setCurrent]=useState(getCurrent),[selected,setSelected]=useState(['group']),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[stream,setStream]=useState('');
  const panel=useRef(null);
  useEffect(()=>{const previous=document.activeElement;panel.current.querySelector('button')?.focus();return()=>previous?.focus();},[]);
  const abort=useRef(null);useEffect(()=>()=>abort.current?.abort(),[]);
  useEffect(()=>{let frame;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>setCurrent(getCurrent()));};const observer=new MutationObserver(update);observer.observe(editor.current,{childList:true,subtree:true,attributes:true,characterData:true});update();return()=>{cancelAnimationFrame(frame);observer.disconnect();};},[getCurrent]);
  const button={padding:'7px 10px',fontSize:12,borderRadius:7,border:`1px solid ${t.surfaceBorder}`,background:t.surface,color:t.text,cursor:'pointer'};
  const field={width:'100%',boxSizing:'border-box',padding:8,borderRadius:7,border:`1px solid ${t.surfaceBorder}`,background:t.inputBg,color:t.text,fontFamily:'inherit',fontSize:12};
  const work=async action=>{if(busy || disabled)return;setBusy(true);setStatus('');try{await action();}catch(e){setStatus(e.message || 'Could not finish.');}finally{setBusy(false);}};
  const fresh=async()=>{const next=await captureSource();setSource(next);return next;};
  const saveFile=(format,item)=>work(async()=>{const snapshot=item || source || await fresh();const blob=await exportBlob(snapshot,format,layout);downloadBlob(blob,`${snapshot.title} ${layout}`,format);setStatus(`${format.toUpperCase()} downloaded from the captured version.`);});
  const points=useMemo(()=>highlightedPoints(current.content,current.fontSize),[current.content,current.fontSize]),slides=outputs.slides || [],packages=outputs.packages || [];
  const saveSlides=next=>onUpdate(previous=>({...previous,slides:typeof next==='function'?next(previous.slides || []):next}));
  async function generate(){
    const settings=structuredClone(profile);await work(async()=>{
      const snapshot=await fresh(),controller=new AbortController();abort.current=controller;let raw='';setStream('');
      const timeout=setTimeout(()=>controller.abort(),190000);
      try{
        await window.callAIStream({system:assistantSystem(DOCUMENT_ASSISTANT_SYSTEM,settings,snapshot.audience)+'\n'+materialsPrompt(selected),messages:[{role:'user',content:JSON.stringify({title:snapshot.title,document:snapshot.text,audience:snapshot.audience,sourceVersion:snapshot.versionId,outputs:selected})}],maxTokens:6500,signal:controller.signal,onChunk:delta=>{raw+=delta;setStream(raw);}});
        const items=parseMaterials(raw);if(!items.length)throw new Error('No complete materials returned. Please try again.');
        onUpdate(previous=>({...previous,packages:[...(previous.packages || []),...items.map(item=>({...item,id:crypto.randomUUID(),createdAt:Date.now(),source:snapshot,profile:settings}))]}));
        const missing=selected.filter(kind=>!items.some(item=>item.kind===kind));setStatus(missing.length?`Saved completed drafts. Missing: ${missing.map(kind=>MATERIALS[kind]).join(', ')}. Generate those again.`:'Drafts saved with their source version. Review before sharing.');setStream('');
      }catch(e){
        const items=parseMaterials(raw);if(items.length)onUpdate(previous=>({...previous,packages:[...(previous.packages || []),...items.map(item=>({...item,id:crypto.randomUUID(),createdAt:Date.now(),source:snapshot,profile:settings,interrupted:true}))]}));
        setStatus(`${e.name==='AbortError'?'Generation stopped.':e.message} ${items.length?'Completed drafts were saved.':'No complete drafts saved.'}`);setStream('');
      }finally{clearTimeout(timeout);abort.current=null;}
    });
  }
  function move(index,direction){saveSlides(previous=>{const next=[...previous];[next[index],next[index+direction]]=[next[index+direction],next[index]];return next;});}
  return <aside ref={panel} role="dialog" aria-modal="true" aria-label="Sermon outputs" onKeyDown={e=>{if(e.key==='Tab'){const controls=[...panel.current.querySelectorAll('button,input,select,textarea,summary')].filter(node=>!node.disabled && node.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey && document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey && document.activeElement===last){e.preventDefault();first?.focus();}e.stopPropagation();}if(e.key==='Escape'){e.stopPropagation();onClose();}}} style={{position:'fixed',inset:'max(16px,4vh) max(16px,8vw)',zIndex:10010,background:t.panelBg,color:t.text,border:`1px solid ${t.surfaceBorder}`,borderRadius:14,boxShadow:'0 12px 50px #0008',padding:16,display:'flex',flexDirection:'column',gap:10}}>
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><strong>Outputs</strong><button style={button} onClick={onClose}>Close outputs</button></div>
    <div role="group" aria-label="Output views" style={{display:'flex',gap:6}}>{[['export','Word / PDF'],['slides','Slide points'],['materials','Materials']].map(([key,label])=><button key={key} style={{...button,background:tab===key?t.accentGrad:t.surface}} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
    {status && <p role="status" style={{fontSize:12,margin:0}}>{status}</p>}
    <div style={{overflow:'auto',flex:1,minHeight:0}}>
    {tab==='export' && <><p style={{fontSize:12,lineHeight:1.6}}>Download a real Word document or PDF. Formatting includes colors, highlights, bold, underline and the editor font size, with 0pt before and after paragraphs.</p><label>Layout <select aria-label="Output layout" value={layout} onChange={e=>setLayout(e.target.value)} style={{...field,width:'auto',margin:8}}><option value="manuscript">Manuscript colors</option><option value="print">Print friendly black</option></select></label><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button style={button} disabled={busy || disabled} onClick={()=>saveFile('docx')}>Download Word</button><button style={button} disabled={busy || disabled} onClick={()=>saveFile('pdf')}>Download PDF</button><button style={button} disabled={busy || disabled} onClick={()=>work(fresh)}>Use latest manuscript</button></div><p style={{fontSize:11,color:t.textMuted,marginTop:12}}>{source?`Captured ${new Date(source.createdAt).toLocaleString()} · Version ${source.versionId}. ${sourceChanged(source,current)?'The manuscript has changed. Use latest manuscript to update exports.':'Exports use this same captured version.'}`:'The first download captures a saved version. Further downloads use that same snapshot until you choose Use latest manuscript.'}</p></>}
    {tab==='slides' && <><p style={{fontSize:12}}>Collect yellow-highlighted points. Edit slide wording separately from the sermon. Source changes are flagged for review.</p><button style={button} disabled={busy || disabled} onClick={()=>work(async()=>{const snapshot=await fresh();saveSlides(previous=>mergeSlides(previous,highlightedPoints(snapshot.content,snapshot.fontSize),snapshot));setStatus('Highlighted points collected. Existing wording and order kept.');})}>Collect highlighted points</button><button style={{...button,marginLeft:8}} disabled={!slides.length || busy} onClick={()=>work(async()=>{downloadBlob(new Blob([slides.map((slide,index)=>`${index+1}. ${slide.text}`).join('\n\n')],{type:'text/plain;charset=utf-8'}),`${current.title} slide points`,'txt');})}>Download slide text</button>
      {!slides.length && <p style={{fontSize:12}}>No queued points yet. Apply Main point formatting to text, then collect.</p>}
      {slides.map((slide,index)=>{const state=slideState(slide,points),point=points.find(point=>point.blockId===slide.blockId && point.index===slide.index);return <article key={slide.id} style={{marginTop:12,padding:10,border:`1px solid ${t.surfaceBorder}`,borderRadius:8}}><strong style={{fontSize:12}}>Slide {index+1}</strong><span style={{fontSize:11,marginLeft:10,color:state==='current'?t.textMuted:'#ffcc70'}}>{state==='current'?'Source current':state==='removed'?'Source removed or no longer highlighted':'Source wording changed'}</span><textarea aria-label={`Slide ${index+1} wording`} value={slide.text} disabled={disabled} rows={2} style={{...field,marginTop:8}} onChange={e=>saveSlides(previous=>previous.map(item=>item.id===slide.id?{...item,text:e.target.value}:item))}/><p style={{fontSize:11,color:t.textMuted}}>Original: {slide.quote}</p><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button style={button} disabled={state==='removed'} onClick={()=>{onClose();onJump(slide.blockId);}}>Go to source</button><button style={button} disabled={disabled || index===0} aria-label={`Move slide ${index+1} up`} onClick={()=>move(index,-1)}>↑</button><button style={button} disabled={disabled || index===slides.length-1} aria-label={`Move slide ${index+1} down`} onClick={()=>move(index,1)}>↓</button><button style={button} disabled={disabled} onClick={()=>saveSlides(previous=>previous.filter(item=>item.id!==slide.id))}>Remove slide</button>{point && state==='changed' && <button style={button} disabled={busy || disabled} onClick={()=>work(async()=>{const snapshot=await fresh();const captured=highlightedPoints(snapshot.content,snapshot.fontSize).find(entry=>entry.blockId===slide.blockId && entry.index===slide.index);if(!captured)throw new Error('Source no longer highlighted. Collect current points instead.');saveSlides(previous=>previous.map(item=>item.id===slide.id?{...item,quote:captured.quote,source:snapshot}:item));})}>Accept current source, keep slide wording</button>}</div></article>;})}
    </>}
    {tab==='materials' && <><p style={{fontSize:12}}>Choose materials to generate together from one saved snapshot. Drafts stay with the sermon and record their source version.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',fontSize:12}}>{Object.entries(MATERIALS).map(([kind,label])=><label key={kind}><input type="checkbox" checked={selected.includes(kind)} disabled={busy} onChange={e=>setSelected(previous=>e.target.checked?[...previous,kind]:previous.filter(item=>item!==kind))}/> {label}</label>)}</div><button style={{...button,marginTop:12}} disabled={busy || disabled || !selected.length} onClick={generate}>Generate selected materials</button>{busy && abort.current && <button style={{...button,marginLeft:8}} onClick={()=>abort.current?.abort()}>Stop generation</button>}{busy && <p role="status">Working from the captured sermon…</p>}
      {stream && <div style={{marginTop:12,fontSize:12,whiteSpace:'pre-wrap'}}>{parseMaterials(stream).map(item=><details key={item.kind} open><summary>{MATERIALS[item.kind]} · received</summary><p>{item.text}</p></details>)}</div>}
      {[...packages].reverse().map(item=><details key={item.id} style={{marginTop:12,border:`1px solid ${t.surfaceBorder}`,padding:10,borderRadius:8}}><summary>{MATERIALS[item.kind]} · {new Date(item.createdAt).toLocaleString()}{sourceChanged(item.source,current)?' · Source changed':''}{item.interrupted?' · Partial batch':''}</summary><p style={{fontSize:11,color:t.textMuted}}>Source version: {item.source.versionId} · {item.source.title}</p><textarea aria-label={`Edit ${MATERIALS[item.kind]} ${item.id}`} value={item.text} rows={12} disabled={disabled} style={field} onChange={e=>onUpdate(previous=>({...previous,packages:previous.packages.map(entry=>entry.id===item.id?{...entry,text:e.target.value,editedAt:Date.now()}:entry)}))}/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:8}}><button style={button} disabled={busy} onClick={()=>saveFile('docx',{...item.source,title:`${item.source.title} ${MATERIALS[item.kind]}`,content:assistantRewriteHtml(item.text)})}>Word</button><button style={button} disabled={busy} onClick={()=>saveFile('pdf',{...item.source,title:`${item.source.title} ${MATERIALS[item.kind]}`,content:assistantRewriteHtml(item.text)})}>PDF</button><button style={button} onClick={()=>work(async()=>{await navigator.clipboard.writeText(item.text);setStatus('Draft copied.');})}>Copy material</button><button style={button} disabled={disabled || busy} onClick={()=>onUpdate(previous=>({...previous,packages:previous.packages.filter(entry=>entry.id!==item.id)}))}>Remove draft</button></div></details>)}
    </>}
    </div>
  </aside>;
}
